### ISSUE TITLE
ground truth images

### ISSUE THREAD

**Issue by Ghulam111** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#12]
what is the shape of ground truth `numpy` color map for each image ? chapter 6 "preparing data for smart car apps".

**Comment by benjaminplanche** [comment]
Dear @Ghulam111,

You can check this, e.g., by printing the shape of the arrays in [Notebook 6.4 - First Glance](https://render.githubusercontent.com/view/ipynb?commit=0562a2307d02d94c4202951771755b96b3f16182&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f5061636b745075626c697368696e672f48616e64732d4f6e2d436f6d70757465722d566973696f6e2d776974682d54656e736f72466c6f772d322f303536326132333037643032643934633432303239353137373137353562393662336631363138322f4368617074657230362f6368365f6e62345f707265706172696e675f646174615f666f725f736d6172745f6361725f617070732e6970796e62&nwo=PacktPublishing%2FHands-On-Computer-Vision-with-TensorFlow-2&path=Chapter06%2Fch6_nb4_preparing_data_for_smart_car_apps.ipynb&repository_id=151050847&repository_type=Repository#First-Glance) (`gt_colors[0].shape`).

The original label maps (containing the per-pixel `trainId`) have the same height and width as the images (1024 x 2048px). Converted into RGB images for visualization, they thus have a 1024 x 2048 x 3px shape (until being opt. resized).

Hoping this helps.
Best,
Benjamin

**Comment by Ghulam111** [comment]
thanks for help
