### ISSUE TITLE
how to use the trained model

### ISSUE THREAD

**Issue by vsanz** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#15]
Hello!

I ran your notebook for chapter8 and I would like to use the trained model for new videos. I am aware this may sound like a super idiotic question, but would you help me using the trained model? how do i save it for later use? and then how would i 'run' it on new videos?

Thanks for your help, and apologies for the basic question,

Veronica.

**Comment by EliotAndres** [comment]
We don't provide the trained model for this notebook. This means that you'll have to train it yourself. 
To save and load a model, have look at the methods here: 
[https://www.tensorflow.org/guide/keras/save_and_serialize](https://www.tensorflow.org/guide/keras/save_and_serialize)

<img width="562" alt="image" src="https://user-images.githubusercontent.com/9083711/77225461-9abf6d80-6b6f-11ea-8824-a448cb258ffb.png">

Regarding instructions on how to run it on new videos, please refer to instructions in the book,

**Comment by vsanz** [comment]
Thank you, Elliot!
