### ISSUE TITLE
Dot product summation on page 29 is not correct 0 or 1 index start?

### ISSUE THREAD

**Issue by edwin-oetelaar** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#17]
Summing the weights of the input and weight vector is not correct.
The inputs are indexed starting at 0, your x0 w0 in all text and pictures.
The conclusion that the dot product is x1 * w1 + x2 * w2 is therefore incorrect it should be
x0 * w0 + x1 * w1 .... etc

For other books reporting this kind or error gets you street cred as a programmer.
https://en.wikipedia.org/wiki/Knuth_reward_check

**Comment by benjaminplanche** [comment]
Good catch, thank you for pointing out this typo!

**Comment by edwin-oetelaar** [comment]
No problem,
Thanks for writing the book.
