### ISSUE TITLE
CH6: in fcn.py, f5_conv3 is not connected to the rest of the model

### ISSUE THREAD

**Issue by Aya-S** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#18]
chapter 6 material: in fcn.py 
in the model definition layer, f5_conv3 ,seems to not be included in the computational graph

**Comment by benjaminplanche** [comment]
Dear @Aya-S,

Sorry for the late answer, and thank you very much for spotting this mistake! I believe I had short-circuited those layers at some point during debug and had forgotten to reconnect them. Indeed, removing the `f5_conv1-3` convolutions layers dramatically decreases the number of parameters in the model and does not significantly impact the accuracy in this use-case. Nevertheless, that was an error from me not to switch back to the proper FCN architecture.

Again, thanks for bringing this to my attention!
