### ISSUE TITLE
Chapter 4 ResNet from scratch doesn't number increase filters for each Macroblock.

### ISSUE THREAD

**Issue by ill10gic** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#21]
The number of filters for each macroblock is 64, but according to the diagrams and white paper, it should be increasing.

**Comment by benjaminplanche** [comment]
Hello @ill10gic,

Thanks a lot for the feedback! Could you specify where you noticed this discrepancy, please? As far as I can tell, the number of filters are being increased as expected, both in the [notebook](../blob/master/Chapter04/ch4_nb1_implement_resnet_from_scratch.ipynb) (c.f. cell 21 where the variable `filters` is multiplied by 2 every block iteration + logs of cell 23 showing the layers' output shapes) and in the corresponding [Python script](../blob/master/Chapter04/resnet_functional.py) (c.f. line [223](../blob/master/Chapter04/resnet_functional.py#L223)).

**Comment by ill10gic** [comment]
I'm so sorry, please disregard! I was following the example from /Hands-On-Computer-Vision-with-TensorFlow-2/Chapter04/ch4_nb1_implement_resnet_from_scratch.ipynb and typing it out until I "understood" it. I realized I missed 
`filters = min(filters * 2, 1024)`
that doubles the filters.

**Comment by benjaminplanche** [comment]
All good, glad it is clarified. :)
